name: Sandbox Build

on:
    push

jobs: 
    build:
        name: Build
        runs-on: ubuntu-latest

        steps:
            - name: Fazendo Checkout do código
              uses: actions/checkout@v2

            - name: Exportando DATABASE_URL para ambiente
              run: echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> $GITHUB_ENV

            - name: Removendo cache do Prisma Client
              run: rm -rf node_modules/.prisma

            - name: Instalando o Node
              uses: actions/setup-node@v4
              with:
                    node-version: 22

            - name: Instalando dependências do node
              run: npm install

            - name: Fazendo o build do projeto
              run: npm run build

            - name: Rodando testes unitários
              run: npm run test